upstream kavach_frontend {
  server frontend:3000;
}

upstream kavach_backend {
  server backend:5000;
}

server {
  listen 80;
  server_name _;
  set $upstream_scheme http;

  client_max_body_size 20m;

  location /api/ {
    proxy_pass $upstream_scheme://kavach_backend;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Request-ID $request_id;
  }

  location /socket.io/ {
    proxy_pass $upstream_scheme://kavach_backend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    proxy_pass $upstream_scheme://kavach_frontend;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
